version: "3.8"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://deniskorolev:@db:5432/radiologary
    depends_on:
      - db

  web_test:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://deniskorolev:@db_test:5432/radiologary_test
    depends_on:
      - db_test

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  nginx_test:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx_test.conf:/etc/nginx/nginx.conf

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: deniskorolev
      POSTGRES_PASSWORD: uy$0pnpo11
      POSTGRES_DB: radiologary
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  db_test:
    image: postgres:13
    environment:
      POSTGRES_USER: deniskorolev
      POSTGRES_PASSWORD: 0000
      POSTGRES_DB: radiologary_test
    ports:
      - "5433:5432"
    volumes:
      - pgdata_test:/var/lib/postgresql/data

volumes:
  pgdata:
  pgdata_test:
