"""deleted links to type and subtype

Revision ID: 0ccb17745c9c
Revises: 33a207c44ebc
Create Date: 2025-09-18 20:49:46.311610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ccb17745c9c'
down_revision = '33a207c44ebc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_subtype', schema=None) as batch_op:
        batch_op.drop_constraint('report_subtype_type_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'report_type', ['type_id'], ['id'])

    with op.batch_alter_table('report_type', schema=None) as batch_op:
        batch_op.drop_constraint('report_type_profile_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_profiles', ['profile_id'], ['id'])

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_constraint('reports_report_subtype_fkey', type_='foreignkey')
        batch_op.drop_column('report_subtype')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_subtype', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('reports_report_subtype_fkey', 'report_subtype', ['report_subtype'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('report_type', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('report_type_profile_id_fkey', 'user_profiles', ['profile_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('report_subtype', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('report_subtype_type_id_fkey', 'report_type', ['type_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
