"""deleted user_email field

Revision ID: 136423e62ad8
Revises: 15e3b6895177
Create Date: 2024-11-25 18:59:16.862137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '136423e62ad8'
down_revision = '15e3b6895177'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_constraint('users_user_email_key', type_='unique')
        batch_op.drop_column('user_email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_email', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('users_user_email_key', ['user_email'])
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
