"""deleted field report_type from ReportTextSnapshot

Revision ID: 33a207c44ebc
Revises: 2597fd23e18b
Create Date: 2025-09-18 19:38:10.209231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33a207c44ebc'
down_revision = '2597fd23e18b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_text_snapshots', schema=None) as batch_op:
        batch_op.drop_column('report_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_text_snapshots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_type', sa.SMALLINT(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
