"""Added tags field to Paragraph and Sentence

Revision ID: 3a10b26f5d39
Revises: a4edade53749
Create Date: 2025-01-30 23:38:21.766462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a10b26f5d39'
down_revision = 'a4edade53749'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_paragraphs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.String(length=255), nullable=True))

    with op.batch_alter_table('sentences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.String(length=255), nullable=True))
        batch_op.alter_column('is_main',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sentences', schema=None) as batch_op:
        batch_op.alter_column('is_main',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.drop_column('tags')

    with op.batch_alter_table('report_paragraphs', schema=None) as batch_op:
        batch_op.drop_column('tags')

    # ### end Alembic commands ###
