"""Remove user_role field from users table

Revision ID: 3a327743e1c9
Revises: 08b1c5a32917
Create Date: 2024-11-23 22:40:46.995109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a327743e1c9'
down_revision = '08b1c5a32917'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('user_role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_role', sa.VARCHAR(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
