"""made head body and tail sentence tables

Revision ID: 3e49552d2cd8
Revises: 641c299b744b
Create Date: 2025-02-16 23:05:55.102699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e49552d2cd8'
down_revision = '641c299b744b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('body_sentences',
    sa.Column('sentence_weight', sa.SmallInteger(), nullable=False),
    sa.Column('sentence', sa.String(length=600), nullable=False),
    sa.Column('tags', sa.String(length=100), nullable=True),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('head_sentences',
    sa.Column('sentence_index', sa.SmallInteger(), nullable=False),
    sa.Column('sentence', sa.String(length=600), nullable=False),
    sa.Column('tags', sa.String(length=100), nullable=True),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tail_sentences',
    sa.Column('sentence_weight', sa.SmallInteger(), nullable=False),
    sa.Column('sentence', sa.String(length=600), nullable=False),
    sa.Column('tags', sa.String(length=100), nullable=True),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tail_sentences')
    op.drop_table('head_sentences')
    op.drop_table('body_sentences')
    # ### end Alembic commands ###
