"""set ondelete=cascade for all tables linked with any user_id

Revision ID: 425b157d979a
Revises: 9ebd5123394b
Create Date: 2025-07-24 15:38:31.393033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '425b157d979a'
down_revision = '9ebd5123394b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('body_sentences', schema=None) as batch_op:
        batch_op.drop_constraint('body_sentences_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('file_metadata', schema=None) as batch_op:
        batch_op.drop_constraint('file_metadata_profile_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_profiles', ['profile_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('head_sentences', schema=None) as batch_op:
        batch_op.drop_constraint('head_sentences_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('key_words_group', schema=None) as batch_op:
        batch_op.drop_constraint('key_words_group_profile_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_profiles', ['profile_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('report_subtype', schema=None) as batch_op:
        batch_op.drop_constraint('report_subtype_type_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'report_type', ['type_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('report_type', schema=None) as batch_op:
        batch_op.drop_constraint('report_type_profile_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_profiles', ['profile_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_constraint('reports_profile_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('reports_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('reports_report_subtype_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_profiles', ['profile_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'report_subtype', ['report_subtype'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('tail_sentences', schema=None) as batch_op:
        batch_op.drop_constraint('tail_sentences_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tail_sentences', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tail_sentences_user_id_fkey', 'users', ['user_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('reports_report_subtype_fkey', 'report_subtype', ['report_subtype'], ['id'])
        batch_op.create_foreign_key('reports_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key('reports_profile_id_fkey', 'user_profiles', ['profile_id'], ['id'])

    with op.batch_alter_table('report_type', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('report_type_profile_id_fkey', 'user_profiles', ['profile_id'], ['id'])

    with op.batch_alter_table('report_subtype', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('report_subtype_type_id_fkey', 'report_type', ['type_id'], ['id'])

    with op.batch_alter_table('key_words_group', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('key_words_group_profile_id_fkey', 'user_profiles', ['profile_id'], ['id'])

    with op.batch_alter_table('head_sentences', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('head_sentences_user_id_fkey', 'users', ['user_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('file_metadata', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('file_metadata_profile_id_fkey', 'user_profiles', ['profile_id'], ['id'])

    with op.batch_alter_table('body_sentences', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('body_sentences_user_id_fkey', 'users', ['user_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###
