"""added lot of fields to users table and model Role and associative teble for users and roles connection

Revision ID: 45d762c712bc
Revises: 136423e62ad8
Create Date: 2024-11-25 19:26:02.830670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45d762c712bc'
down_revision = '136423e62ad8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles_users',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    with op.batch_alter_table('roles_users', schema=None) as batch_op:
        batch_op.create_index('ix_roles_users_user_id_role_id', ['user_id', 'role_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('confirmed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_login_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('current_login_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_login_ip', sa.String(length=45), nullable=True))
        batch_op.add_column(sa.Column('current_login_ip', sa.String(length=45), nullable=True))
        batch_op.add_column(sa.Column('login_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('login_count')
        batch_op.drop_column('current_login_ip')
        batch_op.drop_column('last_login_ip')
        batch_op.drop_column('current_login_at')
        batch_op.drop_column('last_login_at')
        batch_op.drop_column('confirmed_at')
        batch_op.drop_column('password')

    with op.batch_alter_table('roles_users', schema=None) as batch_op:
        batch_op.drop_index('ix_roles_users_user_id_role_id')

    op.drop_table('roles_users')
    op.drop_table('roles')
    # ### end Alembic commands ###
