"""Added report_type_id and user_id to SentenceBase

Revision ID: 49f64dd7b0a5
Revises: a1b291192267
Create Date: 2025-02-22 18:59:00.273905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49f64dd7b0a5'
down_revision = 'a1b291192267'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('body_sentences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_type_id', sa.SmallInteger(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.BigInteger(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('head_sentences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_type_id', sa.SmallInteger(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.BigInteger(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('tail_sentences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_type_id', sa.SmallInteger(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.BigInteger(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tail_sentences', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('report_type_id')

    with op.batch_alter_table('head_sentences', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('report_type_id')

    with op.batch_alter_table('body_sentences', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('report_type_id')

    # ### end Alembic commands ###
