"""deleted temp field in SentenceBase class

Revision ID: 4d303f59628b
Revises: bf199835f503
Create Date: 2025-03-07 16:12:34.832892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d303f59628b'
down_revision = 'bf199835f503'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('body_sentences', schema=None) as batch_op:
        batch_op.drop_column('temp')

    with op.batch_alter_table('head_sentences', schema=None) as batch_op:
        batch_op.drop_column('temp')

    with op.batch_alter_table('tail_sentences', schema=None) as batch_op:
        batch_op.drop_column('temp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tail_sentences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temp', sa.BOOLEAN(), autoincrement=False, nullable=True))

    with op.batch_alter_table('head_sentences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temp', sa.BOOLEAN(), autoincrement=False, nullable=True))

    with op.batch_alter_table('body_sentences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temp', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
