"""Added bold_paragraph field to ReportParagraph

Revision ID: 55b93cf261eb
Revises: 7e4cded1e927
Create Date: 2024-10-05 13:52:24.795063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55b93cf261eb'
down_revision = '7e4cded1e927'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_paragraphs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bold_paragraph', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_paragraphs', schema=None) as batch_op:
        batch_op.drop_column('bold_paragraph')

    # ### end Alembic commands ###
