"""Added cascade delete to key_word_report_link

Revision ID: 563eb44c9846
Revises: 4e1ddf10dc07
Create Date: 2024-09-12 16:20:04.509195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '563eb44c9846'
down_revision = '4e1ddf10dc07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('key_word_report_link', schema=None) as batch_op:
        batch_op.drop_constraint('key_word_report_link_key_word_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('key_word_report_link_report_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'reports', ['report_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'key_words_group', ['key_word_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('key_word_report_link', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('key_word_report_link_report_id_fkey', 'reports', ['report_id'], ['id'])
        batch_op.create_foreign_key('key_word_report_link_key_word_id_fkey', 'key_words_group', ['key_word_id'], ['id'])

    # ### end Alembic commands ###
