"""added teble tail_sentences_groupe and its logic

Revision ID: 5898e6994759
Revises: bc89e230c72d
Create Date: 2025-02-17 00:31:16.082213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5898e6994759'
down_revision = 'bc89e230c72d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tail_sentence_groups',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tail_sentence_group_link',
    sa.Column('tail_sentence_id', sa.BigInteger(), nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['tail_sentence_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tail_sentence_id'], ['tail_sentences.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tail_sentence_id', 'group_id')
    )
    with op.batch_alter_table('tail_sentence_group_link', schema=None) as batch_op:
        batch_op.create_index('ix_tail_sentence_group', ['tail_sentence_id', 'group_id'], unique=False)

    with op.batch_alter_table('tail_sentence_paragraph_link', schema=None) as batch_op:
        batch_op.drop_index('ix_tail_sentence_paragraph')

    op.drop_table('tail_sentence_paragraph_link')
    with op.batch_alter_table('report_paragraphs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tail_sentence_group_id', sa.BigInteger(), nullable=True))
        batch_op.create_foreign_key(None, 'tail_sentence_groups', ['tail_sentence_group_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_paragraphs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('tail_sentence_group_id')

    op.create_table('tail_sentence_paragraph_link',
    sa.Column('tail_sentence_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('paragraph_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['paragraph_id'], ['report_paragraphs.id'], name='tail_sentence_paragraph_link_paragraph_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tail_sentence_id'], ['tail_sentences.id'], name='tail_sentence_paragraph_link_tail_sentence_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tail_sentence_id', 'paragraph_id', name='tail_sentence_paragraph_link_pkey')
    )
    with op.batch_alter_table('tail_sentence_paragraph_link', schema=None) as batch_op:
        batch_op.create_index('ix_tail_sentence_paragraph', ['tail_sentence_id', 'paragraph_id'], unique=False)

    with op.batch_alter_table('tail_sentence_group_link', schema=None) as batch_op:
        batch_op.drop_index('ix_tail_sentence_group')

    op.drop_table('tail_sentence_group_link')
    op.drop_table('tail_sentence_groups')
    # ### end Alembic commands ###
