"""nullable false for rank in Role

Revision ID: 5a95564e9857
Revises: b5b946f293d9
Create Date: 2025-01-22 11:40:31.986901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a95564e9857'
down_revision = 'b5b946f293d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.alter_column('rank',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.alter_column('rank',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
