"""deleted categary_index from ReportCategory class

Revision ID: 6206755f79e4
Revises: a1e765fd2c2c
Create Date: 2025-07-09 13:51:12.337856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6206755f79e4'
down_revision = 'a1e765fd2c2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_categories', schema=None) as batch_op:
        batch_op.drop_column('category_index')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_index', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
