"""changed sentence length from 400 to 600

Revision ID: 641c299b744b
Revises: b44bb1032902
Create Date: 2025-02-16 17:31:28.333267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '641c299b744b'
down_revision = 'b44bb1032902'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sentences', schema=None) as batch_op:
        batch_op.alter_column('sentence',
               existing_type=sa.VARCHAR(length=400),
               type_=sa.String(length=600),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sentences', schema=None) as batch_op:
        batch_op.alter_column('sentence',
               existing_type=sa.String(length=600),
               type_=sa.VARCHAR(length=400),
               existing_nullable=False)

    # ### end Alembic commands ###
