"""added fields str_ and is_additional to report_paragraphs table

Revision ID: 688557ce0476
Revises: c339bbe7ccbf
Create Date: 2025-03-17 12:08:27.837580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '688557ce0476'
down_revision = 'c339bbe7ccbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_paragraphs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('str_before', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('str_after', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_aditional', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###
    
    # Устанавливаем значение False для всех существующих строк
    op.execute("""
        UPDATE report_paragraphs
        SET str_before = FALSE,
            str_after = FALSE,
            is_aditional = FALSE
    """)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_paragraphs', schema=None) as batch_op:
        batch_op.drop_column('is_aditional')
        batch_op.drop_column('str_after')
        batch_op.drop_column('str_before')

    # ### end Alembic commands ###
