"""Add index to key_word_report_link

Revision ID: 6987b2e2e6fe
Revises: e8c50079a00b
Create Date: 2024-09-30 10:14:04.207574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6987b2e2e6fe'
down_revision = 'e8c50079a00b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('key_word_report_link', schema=None) as batch_op:
        batch_op.create_index('ix_key_word_report_link_keyword_report', ['key_word_id', 'report_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('key_word_report_link', schema=None) as batch_op:
        batch_op.drop_index('ix_key_word_report_link_keyword_report')

    # ### end Alembic commands ###
