"""added field index and field weight in links tables

Revision ID: 7215cb2ccbd5
Revises: 49f64dd7b0a5
Create Date: 2025-03-06 15:52:15.748249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7215cb2ccbd5'
down_revision = '49f64dd7b0a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('body_sentence_group_link', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sentence_weight', sa.Integer(), server_default='1', nullable=True))

    with op.batch_alter_table('head_sentence_group_link', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sentence_index', sa.Integer(), nullable=True))

    with op.batch_alter_table('tail_sentence_group_link', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sentence_weight', sa.Integer(), server_default='1', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tail_sentence_group_link', schema=None) as batch_op:
        batch_op.drop_column('sentence_weight')

    with op.batch_alter_table('head_sentence_group_link', schema=None) as batch_op:
        batch_op.drop_column('sentence_index')

    with op.batch_alter_table('body_sentence_group_link', schema=None) as batch_op:
        batch_op.drop_column('sentence_weight')

    # ### end Alembic commands ###
