"""make report_subtype field nullable

Revision ID: 729253196568
Revises: dcf039159c62
Create Date: 2025-09-18 11:20:37.874082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '729253196568'
down_revision = 'dcf039159c62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.alter_column('report_subtype',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.alter_column('report_subtype',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
