"""Add type_paragraph_id to report_paragraphs

Revision ID: 77ca49f33ef3
Revises: afe311aef876
Create Date: 2024-10-07 20:06:34.481136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77ca49f33ef3'
down_revision = 'afe311aef876'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paragraph_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type_name')
    )
    with op.batch_alter_table('report_paragraphs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_paragraph_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'paragraph_types', ['type_paragraph_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_paragraphs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('type_paragraph_id')

    op.drop_table('paragraph_types')
    # ### end Alembic commands ###
