"""added Appconfig table to db

Revision ID: 794e631be2e4
Revises: f7346c4bcb2f
Create Date: 2024-07-27 11:02:04.939403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '794e631be2e4'
down_revision = 'f7346c4bcb2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_key', sa.String(length=50), nullable=False),
    sa.Column('config_value', sa.String(length=200), nullable=False),
    sa.Column('config_user', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['config_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_key')
    )
    with op.batch_alter_table('report_paragraphs', schema=None) as batch_op:
        batch_op.alter_column('paragraph_visible',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_paragraphs', schema=None) as batch_op:
        batch_op.alter_column('paragraph_visible',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))

    op.drop_table('app_config')
    # ### end Alembic commands ###
