"""Add unique constraint on profile_id and config_key

Revision ID: 80ddc775e2e7
Revises: 5a95564e9857
Create Date: 2025-01-22 23:39:46.432358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80ddc775e2e7'
down_revision = '5a95564e9857'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_config', schema=None) as batch_op:
        batch_op.drop_constraint('app_config_config_key_key', type_='unique')
        batch_op.create_unique_constraint('uq_profile_config', ['profile_id', 'config_key'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_config', schema=None) as batch_op:
        batch_op.drop_constraint('uq_profile_config', type_='unique')
        batch_op.create_unique_constraint('app_config_config_key_key', ['config_key'])

    # ### end Alembic commands ###
