"""Add email field to users table

Revision ID: 86c9314c3ebd
Revises: d2bcb02606c8
Create Date: 2024-11-24 20:53:54.854491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86c9314c3ebd'
down_revision = 'd2bcb02606c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))
        
        batch_op.create_unique_constraint(None, ['email'])

    # Копируем данные из user_email в email
    op.execute("UPDATE users SET email = user_email WHERE user_email IS NOT NULL")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('fs_uniquifier',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_column('email')

    # ### end Alembic commands ###
