"""Add type_index to ReportType and subtype_index to ReportSubtype

Revision ID: 8c8765d29ac1
Revises: 6987b2e2e6fe
Create Date: 2024-09-30 10:41:46.416276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c8765d29ac1'
down_revision = '6987b2e2e6fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_subtype', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subtype_index', sa.Integer(), nullable=True))

    with op.batch_alter_table('report_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_index', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_type', schema=None) as batch_op:
        batch_op.drop_column('type_index')

    with op.batch_alter_table('report_subtype', schema=None) as batch_op:
        batch_op.drop_column('subtype_index')

    # ### end Alembic commands ###
