"""deleted type and subtype classes

Revision ID: 8f41bf0075b5
Revises: 0ccb17745c9c
Create Date: 2025-09-18 21:02:20.374516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f41bf0075b5'
down_revision = '0ccb17745c9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report_subtype')
    op.drop_table('report_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_type',
    sa.Column('id', sa.BIGINT(), server_default=sa.text("nextval('report_type_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('type_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('profile_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('type_text', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], name='report_type_profile_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='report_type_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('report_subtype',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('subtype_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('subtype_text', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['report_type.id'], name='report_subtype_type_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='report_subtype_pkey')
    )
    # ### end Alembic commands ###
