"""added field category_1 and catergory_2 for Report

Revision ID: 909cc30ebe01
Revises: f9c4572e1813
Create Date: 2025-07-31 22:03:44.847535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '909cc30ebe01'
down_revision = 'f9c4572e1813'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_1_id', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('category_2_id', sa.BigInteger(), nullable=True))
        batch_op.create_foreign_key(None, 'report_categories', ['category_1_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'report_categories', ['category_2_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('category_2_id')
        batch_op.drop_column('category_1_id')

    # ### end Alembic commands ###
