"""Переименовано поле default на default_profile

Revision ID: 90f6366b8ed3
Revises: bc2ee9deffd8
Create Date: 2024-10-24 14:09:27.030488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90f6366b8ed3'
down_revision = 'bc2ee9deffd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_profile', sa.Boolean(), nullable=True))
        batch_op.drop_column('default')

    op.execute('UPDATE user_profiles SET default_profile = False')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('default_profile')

    # ### end Alembic commands ###
