"""Added comment2 field to Report

Revision ID: 9586753b79fd
Revises: 8c8765d29ac1
Create Date: 2024-09-30 12:12:19.542979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9586753b79fd'
down_revision = '8c8765d29ac1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment2', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_column('comment2')

    # ### end Alembic commands ###
