"""deleted Sentence class

Revision ID: 9fb3c73e4888
Revises: cf030b797de6
Create Date: 2025-03-07 09:36:04.594990

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9fb3c73e4888'
down_revision = 'cf030b797de6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sentences')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sentences',
    sa.Column('paragraph_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('index', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('weight', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('comment', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('sentence', sa.VARCHAR(length=600), autoincrement=False, nullable=False),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('tags', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('sentence_type', postgresql.ENUM('head', 'body', 'tail', name='sentence_type_enum'), autoincrement=False, nullable=False),
    sa.Column('report_type_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['paragraph_id'], ['report_paragraphs.id'], name='sentences_paragraph_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='sentences_pkey')
    )
    # ### end Alembic commands ###
