"""made new field report_type_id nullable false

Revision ID: a1b291192267
Revises: d439cac13439
Create Date: 2025-02-22 18:50:01.977036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b291192267'
down_revision = 'd439cac13439'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sentences', schema=None) as batch_op:
        batch_op.alter_column('report_type_id',
               existing_type=sa.SMALLINT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sentences', schema=None) as batch_op:
        batch_op.alter_column('report_type_id',
               existing_type=sa.SMALLINT(),
               nullable=True)

    # ### end Alembic commands ###
