"""added is_main field in Sentence

Revision ID: a4edade53749
Revises: f30d3ef27c41
Create Date: 2025-01-30 23:12:54.521015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4edade53749'
down_revision = 'f30d3ef27c41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sentences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_main', sa.Boolean(), nullable=True))

    op.execute(
        "UPDATE sentences SET is_main = TRUE WHERE weight = 1 AND index != 0"
    )

    # 3. Для всех остальных предложений ставим is_main=False (чтобы избежать NULL)
    op.execute(
        "UPDATE sentences SET is_main = FALSE WHERE is_main IS NULL"
    )
    
    
    
    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sentences', schema=None) as batch_op:
        batch_op.drop_column('is_main')

    # ### end Alembic commands ###
