"""Add file_description field and updates in FileMetadata model

Revision ID: a7959c63f9ae
Revises: 1997ddbcc7a7
Create Date: 2024-10-14 14:30:36.485485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7959c63f9ae'
down_revision = '1997ddbcc7a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_metadata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_description', sa.String(length=500), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_metadata', schema=None) as batch_op:
        batch_op.drop_column('file_description')

    # ### end Alembic commands ###
