"""deleted field is_main from table sentences

Revision ID: b44bb1032902
Revises: 0b08cacff261
Create Date: 2025-02-12 14:00:20.939227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b44bb1032902'
down_revision = '0b08cacff261'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sentences', schema=None) as batch_op:
        batch_op.drop_column('is_main')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sentences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_main', sa.BOOLEAN(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
