"""added field to filemetadata with ai file id

Revision ID: b9e8bcf308c1
Revises: 0ea841bd67a5
Create Date: 2025-04-22 14:59:44.627577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9e8bcf308c1'
down_revision = '0ea841bd67a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_metadata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_file_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_metadata', schema=None) as batch_op:
        batch_op.drop_column('ai_file_id')

    # ### end Alembic commands ###
