"""Добавлено поле default в UserProfile

Revision ID: bc2ee9deffd8
Revises: a7959c63f9ae
Create Date: 2024-10-24 13:54:34.122528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc2ee9deffd8'
down_revision = 'a7959c63f9ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default', sa.Boolean(), nullable=True))
        
    op.execute('UPDATE user_profiles SET "default" = False WHERE "default" IS NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_column('default')

    # ### end Alembic commands ###
