"""made link tables head_sentence_paragraph_link and tail_sentence_paragraph_link

Revision ID: bc89e230c72d
Revises: 3e49552d2cd8
Create Date: 2025-02-16 23:20:56.915827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc89e230c72d'
down_revision = '3e49552d2cd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('head_sentence_paragraph_link',
    sa.Column('head_sentence_id', sa.BigInteger(), nullable=False),
    sa.Column('paragraph_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['head_sentence_id'], ['head_sentences.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paragraph_id'], ['report_paragraphs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('head_sentence_id', 'paragraph_id')
    )
    with op.batch_alter_table('head_sentence_paragraph_link', schema=None) as batch_op:
        batch_op.create_index('ix_head_sentence_paragraph', ['head_sentence_id', 'paragraph_id'], unique=False)

    op.create_table('tail_sentence_paragraph_link',
    sa.Column('tail_sentence_id', sa.BigInteger(), nullable=False),
    sa.Column('paragraph_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['paragraph_id'], ['report_paragraphs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tail_sentence_id'], ['tail_sentences.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tail_sentence_id', 'paragraph_id')
    )
    with op.batch_alter_table('tail_sentence_paragraph_link', schema=None) as batch_op:
        batch_op.create_index('ix_tail_sentence_paragraph', ['tail_sentence_id', 'paragraph_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tail_sentence_paragraph_link', schema=None) as batch_op:
        batch_op.drop_index('ix_tail_sentence_paragraph')

    op.drop_table('tail_sentence_paragraph_link')
    with op.batch_alter_table('head_sentence_paragraph_link', schema=None) as batch_op:
        batch_op.drop_index('ix_head_sentence_paragraph')

    op.drop_table('head_sentence_paragraph_link')
    # ### end Alembic commands ###
