"""ended add new field is_additional and made its nullable-false

Revision ID: c1875ed4c137
Revises: 09588ffb28e7
Create Date: 2025-03-17 12:23:12.802427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1875ed4c137'
down_revision = '09588ffb28e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_paragraphs', schema=None) as batch_op:
        batch_op.alter_column('is_additional',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.drop_column('is_aditional')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_paragraphs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_aditional', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.alter_column('is_additional',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
