"""db recreation

Revision ID: cbe2722dfca1
Revises: 
Create Date: 2024-06-17 01:27:49.829333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbe2722dfca1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_paragraphs', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'reports', ['report_id'], ['id'])

    with op.batch_alter_table('sentences', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'report_paragraphs', ['paragraph_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sentences', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('report_paragraphs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
