"""deleted fields weight and index on the sentence tables

Revision ID: cf030b797de6
Revises: 7215cb2ccbd5
Create Date: 2025-03-06 19:56:24.869326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf030b797de6'
down_revision = '7215cb2ccbd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('body_sentence_group_link', schema=None) as batch_op:
        batch_op.alter_column('sentence_weight',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('body_sentences', schema=None) as batch_op:
        batch_op.drop_column('sentence_weight')

    with op.batch_alter_table('head_sentence_group_link', schema=None) as batch_op:
        batch_op.alter_column('sentence_index',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('head_sentences', schema=None) as batch_op:
        batch_op.drop_column('sentence_index')

    with op.batch_alter_table('tail_sentence_group_link', schema=None) as batch_op:
        batch_op.alter_column('sentence_weight',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('tail_sentences', schema=None) as batch_op:
        batch_op.drop_column('sentence_weight')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tail_sentences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sentence_weight', sa.SMALLINT(), autoincrement=False, nullable=False))

    with op.batch_alter_table('tail_sentence_group_link', schema=None) as batch_op:
        batch_op.alter_column('sentence_weight',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('head_sentences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sentence_index', sa.SMALLINT(), autoincrement=False, nullable=False))

    with op.batch_alter_table('head_sentence_group_link', schema=None) as batch_op:
        batch_op.alter_column('sentence_index',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('body_sentences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sentence_weight', sa.SMALLINT(), autoincrement=False, nullable=False))

    with op.batch_alter_table('body_sentence_group_link', schema=None) as batch_op:
        batch_op.alter_column('sentence_weight',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))

    # ### end Alembic commands ###
