"""small changes like adding BaseModel to ReportCategory class

Revision ID: d1b3e064eaff
Revises: 909cc30ebe01
Create Date: 2025-08-09 18:03:47.249220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1b3e064eaff'
down_revision = '909cc30ebe01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('body_sentences', schema=None) as batch_op:
        batch_op.alter_column('report_type_id',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=True)

    with op.batch_alter_table('head_sentences', schema=None) as batch_op:
        batch_op.alter_column('report_type_id',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=True)

    with op.batch_alter_table('tail_sentences', schema=None) as batch_op:
        batch_op.alter_column('report_type_id',
               existing_type=sa.SMALLINT(),
               type_=sa.BigInteger(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tail_sentences', schema=None) as batch_op:
        batch_op.alter_column('report_type_id',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=True)

    with op.batch_alter_table('head_sentences', schema=None) as batch_op:
        batch_op.alter_column('report_type_id',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=True)

    with op.batch_alter_table('body_sentences', schema=None) as batch_op:
        batch_op.alter_column('report_type_id',
               existing_type=sa.BigInteger(),
               type_=sa.SMALLINT(),
               existing_nullable=True)

    # ### end Alembic commands ###
