"""Added key_word_report_link and key_word_paragraph_link tables

Revision ID: d4baf54897fc
Revises: 5f7d0accead4
Create Date: 2024-09-09 14:25:01.143010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4baf54897fc'
down_revision = '5f7d0accead4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('key_word_report_link',
    sa.Column('key_word_id', sa.BigInteger(), nullable=False),
    sa.Column('report_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['key_word_id'], ['key_words_group.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('key_word_id', 'report_id')
    )
    op.create_table('key_word_paragraph_link',
    sa.Column('key_word_id', sa.BigInteger(), nullable=False),
    sa.Column('paragraph_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['key_word_id'], ['key_words_group.id'], ),
    sa.ForeignKeyConstraint(['paragraph_id'], ['report_paragraphs.id'], ),
    sa.PrimaryKeyConstraint('key_word_id', 'paragraph_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('key_word_paragraph_link')
    op.drop_table('key_word_report_link')
    # ### end Alembic commands ###
