"""add class ReportCategary

Revision ID: db3031f8d99a
Revises: 9d3e9d9691f9
Create Date: 2025-07-05 19:09:11.737260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db3031f8d99a'
down_revision = '9d3e9d9691f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_categories',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('profile_id', sa.BigInteger(), nullable=True),
    sa.Column('is_global', sa.Boolean(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('category_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['report_categories.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report_categories')
    # ### end Alembic commands ###
