"""added field global_category_id for Report

Revision ID: dcf039159c62
Revises: d1b3e064eaff
Create Date: 2025-09-17 15:47:36.617730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcf039159c62'
down_revision = 'd1b3e064eaff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('global_category_id', sa.BigInteger(), nullable=True))
        batch_op.create_foreign_key(None, 'report_categories', ['global_category_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('global_category_id')

    # ### end Alembic commands ###
