"""Добавляем каскадное удаление и устанавливаем default_profile как False а также добавил поле weight в ReportParagraph

Revision ID: df60a1d91ad0
Revises: 90f6366b8ed3
Create Date: 2024-10-24 16:06:02.657075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df60a1d91ad0'
down_revision = '90f6366b8ed3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_paragraphs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight', sa.SmallInteger(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_paragraphs', schema=None) as batch_op:
        batch_op.drop_column('weight')

    # ### end Alembic commands ###
