"""Make type_paragraph_id non-nullable

Revision ID: e187bcf3bc14
Revises: 77ca49f33ef3
Create Date: 2024-10-07 20:30:24.837525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e187bcf3bc14'
down_revision = '77ca49f33ef3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_paragraphs', schema=None) as batch_op:
        batch_op.alter_column('type_paragraph_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_paragraphs', schema=None) as batch_op:
        batch_op.alter_column('type_paragraph_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
