"""Initial migration for model structure huge changes

Revision ID: e48a3e3aa893
Revises: df60a1d91ad0
Create Date: 2024-10-27 00:07:41.946560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e48a3e3aa893'
down_revision = 'df60a1d91ad0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('key_words_group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_id', sa.BigInteger(), nullable=True))
        batch_op.drop_constraint('key_words_group_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_profiles', ['profile_id'], ['id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('report_paragraphs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paragraph_weight', sa.SmallInteger(), nullable=True))
        batch_op.drop_column('weight')

    with op.batch_alter_table('report_subtype', schema=None) as batch_op:
        batch_op.drop_constraint('report_subtype_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('report_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_id', sa.BigInteger(), nullable=True))
        batch_op.drop_constraint('report_type_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_profiles', ['profile_id'], ['id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_constraint('reports_report_type_fkey', type_='foreignkey')
        batch_op.drop_column('report_type')
        batch_op.drop_column('comment2')

    # ### end Alembic commands ###
    op.execute("UPDATE report_paragraphs SET paragraph_weight = 1 WHERE paragraph_weight IS NULL;")
    op.execute("UPDATE user_profiles SET default_profile = FALSE WHERE default_profile IS NULL;")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment2', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('report_type', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('reports_report_type_fkey', 'report_type', ['report_type'], ['id'])

    with op.batch_alter_table('report_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('report_type_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.drop_column('profile_id')

    with op.batch_alter_table('report_subtype', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('report_subtype_user_id_fkey', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('report_paragraphs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight', sa.SMALLINT(), autoincrement=False, nullable=True))
        batch_op.drop_column('paragraph_weight')

    with op.batch_alter_table('key_words_group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('key_words_group_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.drop_column('profile_id')

    # ### end Alembic commands ###
