"""Added profile_id to Report

Revision ID: e8c50079a00b
Revises: f857ec82ceef
Create Date: 2024-09-29 16:28:42.533708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8c50079a00b'
down_revision = 'f857ec82ceef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_id', sa.BigInteger(), nullable=True))
        batch_op.create_foreign_key(None, 'user_profiles', ['profile_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('profile_id')

    # ### end Alembic commands ###
