"""added indexes for fast search

Revision ID: ef767f5c3a83
Revises: 614f356cb11b
Create Date: 2025-02-17 01:19:23.998541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef767f5c3a83'
down_revision = '614f356cb11b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('body_sentence_group_link', schema=None) as batch_op:
        batch_op.create_index('ix_body_sentence_group_link_group', ['group_id'], unique=False)

    with op.batch_alter_table('body_sentence_groups', schema=None) as batch_op:
        batch_op.create_index('ix_body_sentence_group_id', ['id'], unique=False)

    with op.batch_alter_table('head_sentences', schema=None) as batch_op:
        batch_op.create_index('ix_head_sentence_body_sentence_group', ['body_sentence_group_id'], unique=False)

    with op.batch_alter_table('report_paragraphs', schema=None) as batch_op:
        batch_op.create_index('ix_paragraph_tail_sentence_group', ['tail_sentence_group_id'], unique=False)

    with op.batch_alter_table('tail_sentence_group_link', schema=None) as batch_op:
        batch_op.create_index('ix_tail_sentence_group_link_group', ['group_id'], unique=False)

    with op.batch_alter_table('tail_sentence_groups', schema=None) as batch_op:
        batch_op.create_index('ix_tail_sentence_group_id', ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tail_sentence_groups', schema=None) as batch_op:
        batch_op.drop_index('ix_tail_sentence_group_id')

    with op.batch_alter_table('tail_sentence_group_link', schema=None) as batch_op:
        batch_op.drop_index('ix_tail_sentence_group_link_group')

    with op.batch_alter_table('report_paragraphs', schema=None) as batch_op:
        batch_op.drop_index('ix_paragraph_tail_sentence_group')

    with op.batch_alter_table('head_sentences', schema=None) as batch_op:
        batch_op.drop_index('ix_head_sentence_body_sentence_group')

    with op.batch_alter_table('body_sentence_groups', schema=None) as batch_op:
        batch_op.drop_index('ix_body_sentence_group_id')

    with op.batch_alter_table('body_sentence_group_link', schema=None) as batch_op:
        batch_op.drop_index('ix_body_sentence_group_link_group')

    # ### end Alembic commands ###
