"""added field 'is system' to the table report_types

Revision ID: f2c9b6adcddf
Revises: b9e8bcf308c1
Create Date: 2025-05-10 13:12:36.152486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2c9b6adcddf'
down_revision = 'b9e8bcf308c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_system', sa.Boolean(), nullable=True))

    # Обновляем все существующие строки, устанавливая is_system в False
    op.execute("UPDATE report_type SET is_system = FALSE")

    # Делаем поле NOT NULL после обновления данных
    with op.batch_alter_table('report_type', schema=None) as batch_op:
        batch_op.alter_column('is_system', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_type', schema=None) as batch_op:
        batch_op.drop_column('is_system')

    # ### end Alembic commands ###
