"""added link table paragraph_links

Revision ID: f30d3ef27c41
Revises: ce4e14f0ab73
Create Date: 2025-01-30 18:53:08.773265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f30d3ef27c41'
down_revision = 'ce4e14f0ab73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paragraph_links',
    sa.Column('paragraph_id_1', sa.BigInteger(), nullable=False),
    sa.Column('paragraph_id_2', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['paragraph_id_1'], ['report_paragraphs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paragraph_id_2'], ['report_paragraphs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('paragraph_id_1', 'paragraph_id_2')
    )
    with op.batch_alter_table('paragraph_links', schema=None) as batch_op:
        batch_op.create_index('ix_paragraph_links_paragraphs', ['paragraph_id_1', 'paragraph_id_2'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paragraph_links', schema=None) as batch_op:
        batch_op.drop_index('ix_paragraph_links_paragraphs')

    op.drop_table('paragraph_links')
    # ### end Alembic commands ###
