"""added field is_active and is_impression on the Paragraph class

Revision ID: f8d877f18bb6
Revises: 4d303f59628b
Create Date: 2025-03-12 13:13:36.493761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8d877f18bb6'
down_revision = '4d303f59628b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_paragraphs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_impression', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###

    # ✅ Устанавливаем is_active = True для всех параграфов
    op.execute(
        "UPDATE report_paragraphs SET is_active = TRUE;"
    )

    # ✅ Устанавливаем is_impression = True для тех, у кого paragraph_type = 'impression'
    op.execute(
        "UPDATE report_paragraphs SET is_impression = TRUE WHERE paragraph_type = 'impression';"
    )

    # ✅ Устанавливаем is_impression = False для всех остальных (на всякий случай, если вдруг есть NULL)
    op.execute(
        "UPDATE report_paragraphs SET is_impression = FALSE WHERE paragraph_type != 'impression' OR paragraph_type IS NULL;"
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_paragraphs', schema=None) as batch_op:
        batch_op.drop_column('is_impression')
        batch_op.drop_column('is_active')
    # ### end Alembic commands ###