"""Add ondelete cascade to report_id in report_paragraphs

Revision ID: f9c4572e1813
Revises: 425b157d979a
Create Date: 2025-07-24 16:02:47.815877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9c4572e1813'
down_revision = '425b157d979a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_paragraphs', schema=None) as batch_op:
        batch_op.drop_constraint('report_paragraphs_report_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'reports', ['report_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_paragraphs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('report_paragraphs_report_id_fkey', 'reports', ['report_id'], ['id'])

    # ### end Alembic commands ###
